import type { Metadata } from "next";
import {
  Urbanist,
  Inter,
  Raleway,
  Vesper_Libre,
  Ramaraja,
  Montserrat,
  Lalezar,
  Lancelot, Lateef
} from "next/font/google";
import "./globals.css";

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
const vesper = Vesper_Libre({
  variable: "--font-vesper",
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
});
const ramaraja = Ramaraja({
  variable: "--font-ramaraja",
  subsets: ["latin"],
  weight: ["400"],
});
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
const lalezar = Lalezar({
  variable: "--font-lalezar",
  subsets: ["latin"],
  weight: ["400"],
});
const lancelot = Lancelot({
  variable: "--font-lancelot",
  subsets: ["latin"],
  weight: ["400"],
});
const lateef = Lateef({
  variable: "--font-lateef",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Portgig",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full ">
      <body
        className={`${urbanist.variable} ${inter.variable} ${raleway.variable} ${vesper.variable} ${ramaraja.variable} ${montserrat.variable} ${lalezar.variable}   ${lancelot.variable}    ${lateef.variable} antialiased bg-white`}
        cz-shortcut-listen="true">
        {children}
      </body>
    </html>
  );
}
